services:
  - type: web
    name: csit212-submissions
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn canvas_server:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: MONTCLAIR_EMAIL_PASSWORD
        value: QuFu1234!!
